# Generated by Django 5.1.15 on 2026-03-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_libraryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryrequest',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='libraryrequest',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
